<a href="https://colab.research.google.com/github/venkatbabukr/AllProjects/blob/main/Scaler/Modules/Numpy_Buzz_Terms%2C_Nuances.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview
NumPy = **Numerical Python**

Higly optimized for all numerical calculations, vectorization, matrix operations, transformations etc...

In [60]:
# Setup cell.
# Contains global imports, global variables initialization etc...
#
# For now, always execute this manually when opening a new session...

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define any global variables or configurations here
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

print("Setup cell executed: Common libraries imported and random seed set.")

Setup cell executed: Common libraries imported and random seed set.


# Creation, Initialization, Casting etc...

1. [np.zeros etc...](#scrollTo=0-fxP5T8ekAm&line=1&uniqifier=1)
2. [np.arange](#scrollTo=fyKD6R_Lcy0V&line=5&uniqifier=1)
3. [np.array]()

In [ ]:
import math

arr_allzeros = np.zeros((3, 4))
arr_allones = np.ones((3, 4), dtype='int')
arr_randint = np.random.randint(1,5, size = (3, 4))
arr_allpi = np.full((3, 4), math.pi)

print(f"arr_allzeros:\n{arr_allzeros}")
print(f"\narr_allones:\n{arr_allones}")
print(f"\narr_randint:\n{arr_randint}")
print(f"\narr_allpi:\n{arr_allpi}")

arr_allzeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

arr_allones:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

arr_randint:
[[2 3 4 3]
 [1 3 1 4]
 [4 2 2 4]]

arr_allpi:
[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


In [ ]:
arr1 = np.arange(10)
print(f"np.arange(10) = {arr1}")
print(f"np.arange(5, 16) = {np.arange(5, 16)}")
print(f"np.arange(5, 16, 2) = {np.arange(5, 16, 2)}")

print(f"""
Important attributes:

type(arr1) = {type(arr1)}
arr1.dtype = {arr1.dtype}
arr1.ndim = {arr1.ndim}
arr1.shape = {arr1.shape}
arr1.size = {arr1.size}
arr1.astype('float64) = {arr1.astype('float64')}
""")

np.arange(10) = [0 1 2 3 4 5 6 7 8 9]
np.arange(5, 16) = [ 5  6  7  8  9 10 11 12 13 14 15]
np.arange(5, 16, 2) = [ 5  7  9 11 13 15]

Important attributes:

type(arr1) = <class 'numpy.ndarray'>
arr1.dtype = int64
arr1.ndim = 1
arr1.shape = (10,)
arr1.size = 10
arr1.astype('float64) = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]



In [ ]:
arr2 = np.array([3, 2, 1, 4, 5])
print(f"np.array([3, 2, 1, 4, 5]) = {arr2}")

list_2 = [0,1,2,3,4.83,5,6,7,8,9,10]

arr_2 = np.array(list_2)

print(f"list_2 = {list_2}")
print(f"arr_2 = {arr_2}")

np.array([3, 2, 1, 4, 5]) = [3 2 1 4 5]
list_2 = [0, 1, 2, 3, 4.83, 5, 6, 7, 8, 9, 10]
arr_2 = [ 0.    1.    2.    3.    4.83  5.    6.    7.    8.    9.   10.  ]


# NP Array structure

1. **ndim**: Number of dimensions of the array.
2. **shape**: The tuple describing array's spread/number of elements in each dimension
3. **Axis**: Each dimension becomes axis
    * **In 2D**: ***axis 0*** is ***rows***, ***axis 1*** is ***columns***
    * **In 3D**: ***axis 0*** is the ***stack***, ***axis 1*** is the ***rows***, ***axis 2*** is the ***columns***
4. **size**: Total size or total number of elements in the array = x*y*z... where x, y, z are count in each dimension

# Indexing & Slicing

Approach
```
arr[row_index , col_index]
arr[row_slice, col_slice]
```

**Very imortant note:** All indexing, slicing etc... create views of the array. They don't create a separate copy! See details of [np.shares_memory()](https://numpy.org/doc/2.2/reference/generated/numpy.shares_memory.html) for details...

## Types:

1. [Basic](#scrollTo=H0wMAshcy_lZ&line=2&uniqifier=1)
2. [Boolean indexing](#scrollTo=IWGFIvTx449H&line=2&uniqifier=1)
3. [Fancy indexing](#scrollTo=o6yxbAN659EA&line=1&uniqifier=1)
4. [Assignment using indexing](#scrollTo=8v3CYg-v9W9t&line=13&uniqifier=1)

## Other concepts

1. Slicing and adding dimension

In [48]:
# Basic indexing and slicing

arr1 = np.arange(16).reshape(4, 4)
print(f"arr1:\n{arr1}")
print(f"\nFirst row of arr1 = arr1[0,:] = {arr1[0,:]}")
print(f"\nLast row of arr1 = arr1[-1,:] = {arr1[-1,:]}")
print(f"\nFirst 2 rows of arr1 = arr1[:2] =\n{arr1[:2]}")
print(f"\nSecond column of arr1 = arr1[:,1] = {arr1[:,1]}")
print(f"\nLast column of arr1 = arr1[:,-1] = {arr1[:,-1]}")
print(f"\nAlternate rows of arr1 = arr1[::2,:] =\n{arr1[::2,:]}")
print(f"\nAlternate columns of arr1 = arr1[:,::2] =\n{arr1[:,::2]}")
print(f"\nVertical flip of arr1 = arr1[::-1,:] =\n{arr1[::-1,:]}")
print(f"\nHorizontal flip of arr1 = arr1[:,::-1] =\n{arr1[:,::-1]}")

arr1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

First row of arr1 = arr1[0,:] = [0 1 2 3]

Last row of arr1 = arr1[-1,:] = [12 13 14 15]

First 2 rows of arr1 = arr1[:2] =
[[0 1 2 3]
 [4 5 6 7]]

Second column of arr1 = arr1[:,1] = [ 1  5  9 13]

Last column of arr1 = arr1[:,-1] = [ 3  7 11 15]

Alternate rows of arr1 = arr1[::2,:] =
[[ 0  1  2  3]
 [ 8  9 10 11]]

Alternate columns of arr1 = arr1[:,::2] =
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]

Vertical flip of arr1 = arr1[::-1,:] =
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

Horizontal flip of arr1 = arr1[:,::-1] =
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [38]:
# Boolean indexing
arr1 = np.arange(6)
print(f"arr1: {arr1}")
print(f"\nOdd numbers boolean array = arr1 % 2 == 1 = {arr1 % 2 == 1}")
print(f"\nOdd numbers = arr1[arr1 % 2 == 1] = {arr1[arr1 % 2 == 1]}")
print(f"\nEven numbers boolean array = arr1 % 2 == 0 = {arr1 % 2 == 0}")
print(f"\nEven numbers = arr1[arr1 % 2 == 0] = {arr1[arr1 % 2 == 0]}")

arr1: [0 1 2 3 4 5]

Odd numbers boolean array = arr1 % 2 == 1 = [False  True False  True False  True]

Odd numbers = arr1[arr1 % 2 == 1] = [1 3 5]

Even numbers boolean array = arr1 % 2 == 0 = [ True False  True False  True False]

Even numbers = arr1[arr1 % 2 == 0] = [0 2 4]


In [52]:
# Fancy indexing
arr1 = np.arange(1, 11)
print(f"arr1: {arr1}")
print(f"\nFancy indexing using lists = arr1[[0, 3, 8]] = {arr1[[0, 3, 8]]}")
print(f"\nFancy indexing using range arr1[range(0, 10, 2)] = {arr1[range(0, 10, 2)]}")

arr1: [ 1  2  3  4  5  6  7  8  9 10]

Fancy indexing using lists = arr1[[0, 3, 8]] = [1 4 9]

Fancy indexing using range arr1[range(0, 10, 2)] = [1 3 5 7 9]


In [59]:
# Assignemnt using fancy indexing...

arr1 = np.arange(10)
print(f"arr1: {arr1}")

# Negate all even numbers!
arr1[arr1 % 2 == 0] = -arr1[arr1 % 2 == 0]
print(f"\narr1 after negating even numbers: {arr1}")

arr1 = abs(arr1)
# Negate the whole array!
arr1 = -arr1
print(f"\narr1 after negating the whole array: {arr1}")

arr1: [0 1 2 3 4 5 6 7 8 9]

arr1 after negating even numbers: [ 0  1 -2  3 -4  5 -6  7 -8  9]

arr1 after negating the whole array: [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


# Flatten, Reshape

# Sorting

# Aggregation

# Vectorization, Broadcasting

# Matrix operations