<a href="https://colab.research.google.com/github/venkatbabukr/AllProjects/blob/main/Scaler/Modules/Numpy_Buzz_Terms%2C_Nuances.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview
NumPy = Numerical Python

Higly optimized for all numerical calculations, vectorization, matrix operations, transformations etc...

In [1]:
import numpy as np

# Creation, Initialization, Casting etc...

1. [np.zeros etc...](#scrollTo=0-fxP5T8ekAm&line=1&uniqifier=1)
2. [np.arange](#scrollTo=fyKD6R_Lcy0V&line=5&uniqifier=1)
3. [np.array]()

In [14]:
import math

arr_allzeros = np.zeros((3, 4))
arr_allones = np.ones((3, 4), dtype='int')
arr_randint = np.random.randint(1,5, size = (3, 4))
arr_allpi = np.full((3, 4), math.pi)

print(f"arr_allzeros:\n{arr_allzeros}")
print(f"\narr_allones:\n{arr_allones}")
print(f"\narr_randint:\n{arr_randint}")
print(f"\narr_allpi:\n{arr_allpi}")

arr_allzeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

arr_allones:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

arr_randint:
[[2 3 4 3]
 [1 3 1 4]
 [4 2 2 4]]

arr_allpi:
[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


In [16]:
arr1 = np.arange(10)
print(f"np.arange(10) = {arr1}")
print(f"np.arange(5, 16) = {np.arange(5, 16)}")
print(f"np.arange(5, 16, 2) = {np.arange(5, 16, 2)}")

print(f"""
Important attributes:

type(arr1) = {type(arr1)}
arr1.dtype = {arr1.dtype}
arr1.ndim = {arr1.ndim}
arr1.shape = {arr1.shape}
arr1.size = {arr1.size}
arr1.astype('float64) = {arr1.astype('float64')}
""")

np.arange(10) = [0 1 2 3 4 5 6 7 8 9]
np.arange(5, 16) = [ 5  6  7  8  9 10 11 12 13 14 15]
np.arange(5, 16, 2) = [ 5  7  9 11 13 15]

Important attributes:

type(arr1) = <class 'numpy.ndarray'>
arr1.dtype = int64
arr1.ndim = 1
arr1.shape = (10,)
arr1.size = 10
arr1.astype('float64) = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]



In [12]:
arr2 = np.array([3, 2, 1, 4, 5])
print(f"np.array([3, 2, 1, 4, 5]) = {arr2}")

list_2 = [0,1,2,3,4.83,5,6,7,8,9,10]

arr_2 = np.array(list_2)

print(f"list_2 = {list_2}")
print(f"arr_2 = {arr_2}")

np.array([3, 2, 1, 4, 5]) = [3 2 1 4 5]
list_2 = [0, 1, 2, 3, 4.83, 5, 6, 7, 8, 9, 10]
arr_2 = [ 0.    1.    2.    3.    4.83  5.    6.    7.    8.    9.   10.  ]


# Indexing & Slicing

## Types:

1. Basic
2. Boolean indexing
3. Fancy indexing

## Other concepts

1. Slicing and adding dimension

# Flatten, Reshape

# Sorting

# Aggregation

# Vectorization, Broadcasting