$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. Even and odd**

a. Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

b. Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

#### **Ans:**

```python
a. np.arange(22, 71, 2)
b. np.arange(21, 72, 2)
```

# **Q2. Cast a type**

Raghu has created a numpy array arr using the following code:

```python
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
```

He wants to change the data type from integer to float. How to cast?

#### **Ans:**

```python
np.astype('float64')
```

# **Q3. Slice away**

What woud be the output of the following code :

```python
import numpy as np
a = np.arange(10)
print(a[2:5])
```

In [4]:
import numpy as np
a = np.arange(10)
print(a[2:5])

[2 3 4]


# **Q4. What about output?**

What is the output of the following code snippet?

```python
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10])
x[(x >= -5) & (x <= 15)] *= -1
print(x)
```

In [5]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10]


# **Q5. Shape of you**

**Problem statement:**

Given an array, return the shape and dimension of the array.

**Input Format:**

A numpy array

**Output Format:**

A Tuple (shape, dim)

**Sample Input:**

[0 1 2 3 4 5]

**Sample Output:**

((6,), 1)

In [6]:
import numpy as np

def get_array_properties(arr):
    '''
    INPUT: arr -> A nD array

    OUTPUT: result -> tuple consisting of shape and dimension
    '''

    ## STEP 1. Get the shape of array

    shape = arr.shape

    ## STEP 2. Get the dimension of array

    dim = arr.ndim


    return shape,dim

arr = np.array([0, 1, 2, 3, 4, 5])
print(f"get_array_properties({arr}) = ${get_array_properties(arr)}")

get_array_properties([0 1 2 3 4 5]) = $((6,), 1)


# **Q6. Index of Pokédex**

**Problem Statement:**

Given a 1D array, return the first and last elements from the array.

**Input Format:**

> **NOTE:** No need to take the input explicitly, the input-handling code is already in place.

A 1D numpy array

**Output Format:**

A tuple (first_element, last_element)

**Sample Input:**

[0, 1, 2, 3, 4, 5]

**Sample Output:**

(0, 5)

In [7]:
import numpy as np

def get_elements(arr):
    '''
    INPUT: arr -> 1D numpy array

    OUTPUT elements -> tuple of first and last element.
    '''
    return arr[0], arr[-1]

arr = np.array([0, 1, 2, 3, 4, 5])
print(f"get_elements({arr}) = ${get_elements(arr)}")

get_elements([0 1 2 3 4 5]) = $(np.int64(0), np.int64(5))


# **Q7. Create the sequence**

Create a sequence of a given length from a given start point, where the difference between 2 consecutive elements of the expected sequence is also given as step.

**Input Format:**

One line of input will have 3 space-separated integers consisting of start, length of sequence and step between two continuous elements of the sequence.

**Output Format:**

A numpy array of integers

**Sample Input:**

5 10 3

**Sample Output:**

[5 8 11 14 17 20 23 26 29 32]

**Note:** You can use either .arange() or .linspace() to solve this question.

In [11]:
import numpy as np
def seq(start, length, step):
    ''' start, length and step are in form of integers all representing the attributes as their names suggest
        output -> A numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    # Using arange:
    # return np.arange(start, start + length * step, step)

    # Using linspace
    return np.linspace(start, start + length * step, length, False).astype(int)

start = 5
length = 10
step = 3
print(f"seq({start}, {length}, {step}) = {seq(start, length, step)}")

seq(5, 10, 3) = [ 5  8 11 14 17 20 23 26 29 32]


# **Q8. The dawn of the planet of numpy**

**Problem Statement:**


Given the start, end, and the stepsize return a numpy array sequence in given range with the specified stepsize.

**Input Format:**

One line of input will have 3 space-separated numbers consisting of start, end of sequence and step.

**Output Format:**

A numpy array with elements rounded off to 2 decimal places.

**Sample Input:**

5 7 0.5

**Sample Output:**

[5 5.5 6 6.5]

**Note:** To round off the numpy array, use np.round()

In [12]:
import numpy as np

def create_seq(start, end, step):
    '''
    INPUT: start, end, step

    OUTPUT: arr -> 1D numpy array

    '''
    return np.arange(start, end, step).round(2)

start = 5
end = 7
step = 0.5

print(f"create_seq({start}, {end}, {step}) = {create_seq(start, end, step)}")

create_seq(5, 7, 0.5) = [5.  5.5 6.  6.5]


# **AQ1. Index operation**

What would be the output for the following code :

```python
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2])
```

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2])


6


# **AQ2. Comparison Returns!**

What will be the output of the following code?


```python
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)
```

In [14]:
import numpy as np

a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)


[False  True False  True]


# **AQ3. Numpy Indexing**

Given a numpy array,

`
arr : array([10, 12, 15, 17, 2, 5, 4, 6])
`

Which of the following is NOT the correct way to access the values at even indices (0,2,4...)?

**Options:**
1. arr[0,2,4,6]
2. arr[[0,2,4,6]]
3. arr[::2]

#### **Ans:**

Option 1: arr[0, 2, 4, 6]

# **AQ4. Multiple Assignment**

What will be the output of the following code?

```python
arr = np.array([1,2,3,4,5,6,7,8])
arr[::2] = range(10,50,10)
print(arr)
```

In [15]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
arr[::2] = range(10,50,10)
print(arr)

[10  2 20  4 30  6 40  8]


# **AQ5. Distinction**

**Problem Statement:**

You are given a numpy array containing marks of students in a class. The student gets distinction or first-division on the basis of the below criteria.

* marks >= 80 : Distinction
* 60 <= marks < 80 : First Division

Find the ratio of number of students who got distinction to the number of students who got first division.


**Input Format:**

A numpy array

**Output Format:**

A float number.

**Sample Input:**

array([20, 35, 68, 82, 83, 70, 90])

**Sample Output:**

1.5

**Sample Explanation:**

Distinction marks are 82, 83 and 90. So, 3 distinctions. First division marks are 68, 70. So 2 first divisions. Ratio = 3/2 = 1.5.

In [17]:
import numpy as np
def ratio(marks_arr):
    # Complete the missing code
    distinction = marks_arr[marks_arr >= 80].shape[0]
    first_division = marks_arr[(marks_arr >= 60) & (marks_arr < 80)].shape[0]
    return distinction / first_division

marks_arr = np.array([20, 35, 68, 82, 83, 70, 90])
print(f"ratio({marks_arr}) = {ratio(marks_arr)}")

ratio([20 35 68 82 83 70 90]) = 1.5
