$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. What about code?**

What is the output of the following code?

```python
import numpy as np
arr = 2 * np.arange(0,2,0.5)
if arr <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy")
```

In [20]:
import numpy as np
arr = 2 * np.arange(0,2,0.5)
if arr <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

# Correct code:
import numpy as np
arr = 2 * np.arange(0,2,0.5)
if np.any(arr <= 0.6):
    print("condition satisfies")
else:
    print("condition doesn't satisfy")


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# **Q2. What will be printed?**

Mark the options which are true about the outputs for code snippets a and b.

Code Snippet a:

```python
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])
```

Code Snippet b:

```python
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])
```

Options:

1. For 'a', the answer is 1.0
2. For 'a', the answer is 2.0
3. For 'b', the answer is 21
4. The code in 'b' will throw ValueError.

#### **Ans:**

1. For 'a' the answer is 1.0
3. For 'b' the answer is 21

In [32]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print(f"""
Broadcasts:

x =
{x}
shape: {x.shape}

v =
{v}
shape: {v.shape}

v[:,None]=
{v[:,None]}
shape: {v[:, None].shape}

Broadcast example1 x / v[:,None]:
{x / v[:,None]}

Broadcast example2 x / v:
{x / v}
""")

import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])

print(f"""
p =
{p}
Shape: {p.shape}

q =
{q}
Shape: {q.shape}

Broadcast example2 p + q:
{p + q}
""")



Broadcasts:

x =
[[200 200 200]
 [300 300 300]
 [400 400 400]]
shape: (3, 3)

v =
[200 300 400]
shape: (3,)

v[:,None]=
[[200]
 [300]
 [400]]
shape: (3, 1)

Broadcast example1 x / v[:,None]:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Broadcast example2 x / v:
[[1.         0.66666667 0.5       ]
 [1.5        1.         0.75      ]
 [2.         1.33333333 1.        ]]


p =
[[ 0]
 [10]
 [20]]
Shape: (3, 1)

q =
[10 11 12]
Shape: (3,)

Broadcast example2 p + q:
[[10 11 12]
 [20 21 22]
 [30 31 32]]



# **Q3. Batchmate's code**

Your batchmate writes the following code, what is the output?

```python
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())
```

In [33]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


# **Q4. The Mask**

**Problem Statement:**

Given an array of marks, return the array only containing elements with marks > 40

**Input Format:**

A 1D numpy array

**Output Format:**

A 1D numpy array

**Sample Input:**

[85, 18, 2, 57, 65, 44]

**Sample Output:**

[85, 57, 65, 44]

In [34]:
import numpy as np

def filter_marks(marks):
    '''
    INPUT: marks -> 1D array

    OUTPUT: filtered_marks -> 1D array
    '''

    ### Step 1 Get the mask for marks > 40
    filter_marks = marks > 40

    ### Step 2 Use the mask to filter the marks
    return marks[filter_marks]

marks = np.array([85, 18, 2, 57, 65, 44])
print(f"filter_marks({marks}) = ${filter_marks(marks)}")

filter_marks([85 18  2 57 65 44]) = $[85 57 65 44]


# **Q5. Indexed array**

Given the following code, what will be the output?

```python
import numpy as np
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])
```

In [37]:
import numpy as np
a = np.array([[34, 28, 55], [8, 56, 3], [77, 87, 19]])
print(f"""
a=
{a}

a^T=
{a.transpose()}

a^T[-2,-2]=
{a.transpose()[-2,-2]}
""")


a=
[[34 28 55]
 [ 8 56  3]
 [77 87 19]]

a^T=
[[34  8 77]
 [28 56 87]
 [55  3 19]]

a^T[-2,-2]=
56



# **AQ1. One for All**

**Problem Statement:**

Given a numpy array and target value k,

Return True if all elements of array satisfy all below given conditions

* Multiple of 2
* Greater than k

**Input Format:**

The input has two lines
* First line is the array
* Second line is the integer value k

**Output Format:**

Boolean value i.e. True or False

**Sample Input:**
```
[0, 1, 2, 3, 4, 5, 6, 7, 8]
3
```

**Sample Output:**
False

**Sample Input:**
```
[8, 12, 16, 20]
4
```

**Sample Output:**
True

In [38]:
import numpy as np

def check_conditions(arr, k):
    '''
    INPUT: arr, k

    OUTPUT: result -> bool
    '''

    result = None
    result = np.all((arr % 2 == 0) & (arr > k))
    return result

arr = np.arange(0, 9)
print(f"check_conditions({arr}, 3) = {check_conditions(arr, 3)}")

arr = np.arange(8, 21, 4)
print(f"check_conditions({arr}, 4) = {check_conditions(arr, 4)}")

check_conditions([0 1 2 3 4 5 6 7 8], 3) = False
check_conditions([ 8 12 16 20], 4) = True


# **AQ2. Extract sub array**

Problem Statement:

Given a 2d array, write a program to return a subarray such that the subarray consists of the elements from:

1. the second to the fourth row of the original array,
2. the elements in these rows should be from the last three columns of the corresponding rows of the original array,
3. the rows should be in reversed order.

**Sample Input:**

```
[[ 0,  1,  2,  3],  
 [ 4,  5,  6,  7],   
 [ 8,  9, 10, 11],   
 [12, 13, 14, 15],   
 [16, 17, 18, 19]]
```

**Sample Output:**
```
array([[13, 14, 15],  
       [ 9, 10, 11],
       [ 5,  6,  7]])
```

In [40]:
import numpy as np


def extract_subarray(arr):
    '''
    INPUT: arr -> 2D array

    OUPUT: result -> 2D array
    '''
    sub_array = arr[1:4]
    return sub_array[:, -3:][::-1]

arr = np.array(
[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]]
)
print(f"""
arr:
{arr}

extract_subarray:
{extract_subarray(arr)}
""")


arr:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

extract_subarray:
[[13 14 15]
 [ 9 10 11]
 [ 5  6  7]]



# **AQ3. Transpose Reshaped**

What would the following code print?

```python
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)
```

In [41]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


# **AQ4. ORDER ORDER ORDER**

**Problem Statement:**

Given a 2D numpy array, return array with its values in the column reversed.

**Input Format:**

A 2D numpy array

**Output Format:**

A 2D numpy array

**Sample Input:**

```
[[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]]
```

**Sample Output:**

```
[[2, 1, 0],
 [5, 4, 3],
 [8, 7, 6]]
```

In [42]:
import numpy as np

def reverse_column(arr):
    '''
    INPUT: arr -> 2D array

    OUTPUT rev_arr -> 2D array
    '''

    rev_arr = arr[:, ::-1]

    return rev_arr

arr = np.array(
[[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]]
)
print(f"""
arr:
{arr}

reverse_column(arr):
{reverse_column(arr)}
""")


arr:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

reverse_column(arr):
[[2 1 0]
 [5 4 3]
 [8 7 6]]



# **AQ5. Rotate the array**

**Problem Statement:**

Given an array in form of a matrix of size (n, n), rotate the matrix clockwise by $90^0$.

**Input Format:**

A 2d numpy array

**Output Format:**

A 2d numpy array

**Sample Input:**
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

**Sample Output:**
```
[[7 4 1]
 [8 5 2]
 [9 6 3]]
```

**Note:** Try Transpose / reversing.

In [46]:
import numpy as np
def rotate_90(mat):
    '''mat -> A 2d numpy array
       output -> A 2d numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    return mat[::-1,:].T

arr = np.arange(1, 10).reshape(3, 3)
print(f"""
arr
{arr}

rotate_img(arr)
{rotate_90(arr)}
""")


arr
[[1 2 3]
 [4 5 6]
 [7 8 9]]

rotate_img(arr)
[[7 4 1]
 [8 5 2]
 [9 6 3]]

