In [ ]:
#import necessary libraries

import numpy as np

#Aggregate functions

* np.sum()
* np.mean()
* np.median()
* np.min()
* np.max()

##Aggregate functions on 1D arrays

In [ ]:
array_1 = np.zeros(shape=(15,))
print(array_1)
print()

array_2 = np.ones(shape=(15,))
print(array_2)
print()


array_3 = np.random.randint(low=0, high=100, size = (15,))
print(array_3)
print()



#range(start, stop, step) ----> np.arange(start,stop,stop)
array_4 = np.arange(10, 24+1)
print(array_4)
print()


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[88 84 70 57 52 11 73 76 34 24 48 11 47 93 85]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [ ]:
#sum of numbers
print("sum =",np.sum(array_2))
print()
print(array_2)

sum = 15.0

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#sum of numbers
print("max =",np.max(array_3))
print()
print("min =",np.min(array_3))
print()

max = 93

min = 11



In [ ]:
#alternate approach

array_3.min()

11

##Aggregate functions on 2D arrays

In [ ]:
arr_2d = np.array(
                    [
                       [  1,  2,    3],
                       [ 10, 20,   30],
                       [100, 200, 300],
                       [  1,   1,   1]

                    ]

)

print(arr_2d)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]
 [  1   1   1]]


In [ ]:
print(np.sum(arr_2d))

276


In [ ]:
#row sums

print(np.sum(arr_2d, axis=1))

[  6  60 600   3]


In [ ]:
#column sums

print(np.sum(arr_2d, axis=0))

[112 223 334]


#Sorting

##Sorting a 1D array

In [ ]:
#Sorting a 1D array

array_1 = np.array([15,18,7,24,-21,22,8,-10,11])


#np.sort()

print(array_1)
print()
print(np.sort(array_1))
print()
print(array_1)


[ 15  18   7  24 -21  22   8 -10  11]

[-21 -10   7   8  11  15  18  22  24]

[ 15  18   7  24 -21  22   8 -10  11]


In [ ]:
#arr_obj.sort()


array_2 = np.array([15,18,7,24,-21,22,8,-10,11])


print(array_2)
print()
print(array_2.sort())
print()
print(array_2)



[ 15  18   7  24 -21  22   8 -10  11]

None

[-21 -10   7   8  11  15  18  22  24]


In [ ]:
#Sorting in DESC order

#Method 1

print(array_1)
print()
print(np.sort(array_1)[::-1]) #reversing the result


[ 15  18   7  24 -21  22   8 -10  11]

[ 24  22  18  15  11   8   7 -10 -21]


In [ ]:
#Another method of sorting

print(array_1)
print()
print(-array_1)
print()
print(np.sort(-array_1))
print()
print(-np.sort(-array_1))


[ 15  18   7  24 -21  22   8 -10  11]

[-15 -18  -7 -24  21 -22  -8  10 -11]

[-24 -22 -18 -15 -11  -8  -7  10  21]

[ 24  22  18  15  11   8   7 -10 -21]


##Sorting a 2D array

In [ ]:
#2D array

lst_2d = [
    [5,    -7,   46],
    [19,   88,   81],
    [-10, -50,    0],
    [1,     2,    3]
]

arr_2d = np.array(lst_2d)

print(arr_2d)

[[  5  -7  46]
 [ 19  88  81]
 [-10 -50   0]
 [  1   2   3]]


In [ ]:
#We will do a simple sort of the above 2d array

print(np.sort(arr_2d))

#observation: For 2d arrays, the default axis = 1

#strictly speaking: the default axis = -1

[[ -7   5  46]
 [ 19  81  88]
 [-50 -10   0]
 [  1   2   3]]


In [ ]:
#column wise sorting, along axis = 0

print(np.sort(arr_2d, axis=0))

[[-10 -50   0]
 [  1  -7   3]
 [  5   2  46]
 [ 19  88  81]]


In [ ]:
#sort the above 2d array along axis = 1



In [ ]:
#sort the above 2d array along axis = 0



In [ ]:
#axis = None
#It first flattens the 2d array, and then sorts the flattened array

print(np.sort(arr_2d, axis=None))

[-50 -10  -7   0   1   2   3   5  19  46  81  88]


In [ ]:
shape_of_array = arr_2d.shape

flattened_arr_2d = arr_2d.flatten()

sorted_flattened_arr_2d = np.sort(flattened_arr_2d)

print(sorted_flattened_arr_2d.reshape(shape_of_array))

[[-50 -10  -7]
 [  0   1   2]
 [  3   5  19]
 [ 46  81  88]]


##argsort() : used to sort the indexes

In [ ]:
marks = np.array([67, 33, 60, 55, 100, 90, 78])

names = np.array(['A','B','C','D','E','F','G'])



argmax()

In [ ]:
#argmax()

marks = np.array([67, 33, 60, 55, 100, 90, 78])

names = np.array(['A','B','C','D','E','F','G'])

print(np.argmax(marks))

In [ ]:
#name of the person with the highest marks



In [ ]:
#argmin()

marks = np.array([67, 33, 60, 55, 100, 90, 78])

names = np.array(['A','B','C','D','E','F','G'])



#Multiplication

In [ ]:
#multiplying two vectors

a = np.array([5,7,10])
b = np.array([10,100,1000])

print(a*b)

[   50   700 10000]


In [ ]:
#Can I do this?


a2 = np.array([5,7,10])
b2 = np.array([10,100,1000,55,99])

print(a2*b2)

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [ ]:
#multiply a with a scalar (not SCALER) value of 5

print(a*5)

In [ ]:
#Let's take another two arrays

c = np.array([5,10])
d = np.array([1,2,3,4])

print(c*d)



Element-wise multiplication of matrices

In [ ]:
m1 = np.array([
                [1, 2],
                [3, 4]
             ])


m2 = np.array([
                [10, 1],
                [5, 55]
             ])

print(m1)
print()
print(m2)
print()
print(m1 * m2)

Multiply Vector / Matrix with Scalar

In [ ]:
v = np.arange(1,6) #vector

s = 100 #scalar

print(v)

print(v*s)

[1 2 3 4 5]
[100 200 300 400 500]


#Vectorization

##How vectorization works

##Converting legacy functions to work on numpy arrays

* np.vectorize( )

In [ ]:
#Custom fuction that takes a number
#and rounds it to the nearest integer

def round_to_integer(x):

  if x >= 0:  #if the input is non-negative

              decimal_part_of_x = x - int(x)

              if decimal_part_of_x >= 0.5:
                return int(x)+1

              else:
                return int(x)

  elif x < 0: #if the input is negative

              decimal_part_of_x = -(x - int(x))

              if decimal_part_of_x >= 0.5:
                  return int(x)-1

              else:
                return int(x)


In [ ]:
#Testing the round_to_integer() function

x1 = 32.49
print(f"{x1} after rounding: {round_to_integer(x1)}")
print()

x2 = -5.6
print(f"{x2} after rounding:  {round_to_integer(x2)}")
print()


x3 = np.array([98.6, 98.8, 98.1, 98.4])
print(f"{x3} after rounding: {round_to_integer(x3)}")
print()


Fahrenheit to Celcius

In [ ]:
#Custom fuction that takes a temp value in deg_Fahrenheit
#and returns the corresponding value in deg_Celcius

def fahrenheit_to_celcius(temp_F):
  return (temp_F - 32) * (5/9)

In [ ]:
#Testing the fahrenheit_to_celcius() function

t1 = 32
print(f"{t1} deg_F = {fahrenheit_to_celcius(t1)} deg_C")
print()

t2 = -5.6
print(f"{t2} deg_F = {fahrenheit_to_celcius(t2)} deg_C")
print()

t3 = np.array([98.6, 98.8, 98.1, 98.4])
print(f"{t3} deg_F = {fahrenheit_to_celcius(t3)} deg_C")
print()

#Broadcasting

In [ ]:
a = np.array([1,2,3])

print(a+10)

[11 12 13]


In [ ]:
a = np.array([1,2,3]) #shape of a = (3,)

b = np.array([10,20]) #shape of b = (2,)

print(a+b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
def func(x, y):
    return x * y


arr_1 = np.array([
                    [ 2,  3,  4,  5],
                    [ 1,  7,  3,  5],
                    [ 2,  8,  6,  9],
                    [11, 23, 12, 19]
                  ])
#shape of arr_1 = (4,4)



arr_2 = np.array([
                    [2,2,2,2]
                  ])

#shape of arr_2 = (1,4)

In [ ]:
func(arr_1,arr_2)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
x = np.arange(6).reshape(3,2)

y = np.array([7,9])

In [ ]:
print(x.shape)

(3, 2)


In [ ]:
print(y.shape)

(2,)


In [ ]:
print(x*y) #shape: (3,2)

[[ 0  9]
 [14 27]
 [28 45]]


#Q&A segment discussions

In [ ]:
print(a)
print(np.sum(a[0:9]))
print(np.sum(a))

[1 2 3]
6
6


In [ ]:
x1 = [1,2,3]

x2 = [
        [1,2,3]

      ]


x3 = [
        [1],
        [2],
        [3]

      ]


x1=np.array(x1) #1D array
x2=np.array(x2) #2D array
x3=np.array(x3) #2D array

In [ ]:
print(x1)
print()
print(x1.shape)

[1 2 3]

(3,)


In [ ]:
print(x2)
print()
print(x2.shape)

[[1 2 3]]

(1, 3)


In [ ]:
print(x3)
print()
print(x3.shape)

[[1]
 [2]
 [3]]

(3, 1)
