$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. Matrix elements**

What will be the outcome of the following code snippet ?

```python
x = np.ones((5,5))
x[1:-1,1:-1] = 0
```

In [1]:
import numpy as np
x = np.ones((5,5))
print(f"""
x=
{x}
""")
x[1:-1,1:-1] = 0
print(f"""
After x[1:-1,1:-1]=0
{x}
""")


x=
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


After x[1:-1,1:-1]=0
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



# **Q2. mapping in numpy**

Given the NumPy array arr, which of the following line of code will return the expected output?

```python
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
```

**Expected output:**

```
array ([[4,6,8,10],
 [2,14,6,10],
 [4,16,12,18],
 [22,46,24,38]])
```

a.
```python
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)
```

b.
```python
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)
```

c.
```python
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)
```

#### **Ans:**

All 3 options a, b, c!

In [4]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
print(f"""Option 1:
{vec(arr,arr1)}
""")

arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
print(f"""Option 2:
{vec(arr,arr1)}
""")

arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
print(f"""Option 3:
{vec(arr,arr1)}
""")

Option 1:
[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]

Option 2:
[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]

Option 3:
[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]



# **Q3. Specific elements**

**Problem Statement:**

Given two 2D arrays, row and column ranges,

Perform the following operations:

* Find the matrix multiplication of the given two matrices and
extract the elements from the output of above step using the given ranges
* If matrix multiplication is not possible, return -1

**Note:** The end points (upper range) of both rows and columns are excluded.

In [6]:
import numpy as np
def specific_elements(mat1,mat2,r1,r2,c1,c2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''

    # STEP1 CHECK whether matrix multiplication is possible
    if mat1.shape[1] != mat2.shape[0]:
      return -1

    ## STEP 2 Perform matrix multiplication

    matmul_array = np.matmul(mat1, mat2)

    ## STEP 3 slice the array based on range value

    result = matmul_array[r1:r2, c1:c2]

    return result

mat1 = np.array(
[
    [6, 6, 4, 7, 9],
    [0, 2, 2, 9, 3],
    [6, 0, 2, 5, 2],
    [2, 4, 3, 5, 5]
])
mat2 = np.array(
[
    [8, 6, 6, 8, 3],
    [2, 7, 0, 3, 1],
    [3, 2, 1, 5, 2],
    [7, 0, 7, 6, 8],
    [1, 5, 6, 4, 5]
])

r1, r2, c1, c2 = (1, 3, 2, 4)
print(f"""
mat1:
{mat1}

mat2:
{mat2}

(r1,r2,c1,c2) = ({r1},{r2},{c1},{c2})

specific_elements(mat1,mat2,r1,r2,c1,c2) =
{specific_elements(mat1,mat2,r1,r2,c1,c2)}

""")

mat1 = np.array(
[
    [6, 6, 4, 7],
    [0, 2, 2, 9],
    [6, 0, 2, 5],
    [2, 4, 3, 5]
])
mat2 = np.array(
[
    [8, 6, 6, 8, 3],
    [2, 7, 0, 3, 1],
    [3, 2, 1, 5, 2],
    [7, 0, 7, 6, 8],
    [1, 5, 6, 4, 5]
])

r1, r2, c1, c2 = (1, 3, 2, 4)
print(f"""
mat1:
{mat1}

mat2:
{mat2}

(r1,r2,c1,c2) = ({r1},{r2},{c1},{c2})

specific_elements(mat1,mat2,r1,r2,c1,c2) =
{specific_elements(mat1,mat2,r1,r2,c1,c2)}

""")


mat1:
[[6 6 4 7 9]
 [0 2 2 9 3]
 [6 0 2 5 2]
 [2 4 3 5 5]]

mat2:
[[8 6 6 8 3]
 [2 7 0 3 1]
 [3 2 1 5 2]
 [7 0 7 6 8]
 [1 5 6 4 5]]

(r1,r2,c1,c2) = (1,3,2,4)

specific_elements(mat1,mat2,r1,r2,c1,c2) =
[[83 82]
 [85 96]]



mat1:
[[6 6 4 7]
 [0 2 2 9]
 [6 0 2 5]
 [2 4 3 5]]

mat2:
[[8 6 6 8 3]
 [2 7 0 3 1]
 [3 2 1 5 2]
 [7 0 7 6 8]
 [1 5 6 4 5]]

(r1,r2,c1,c2) = (1,3,2,4)

specific_elements(mat1,mat2,r1,r2,c1,c2) =
-1




# **Q4. Sort the birds**

**Problem Description:**

Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)

**Input Format:**

Two 1D array list i.e. bird array and age array

**Output Format:**

A 1D array

**Sample Input:**

```
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
```

**Sample Output:**

```
['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'spoonbills', 'Cranes', 'plovers', 'spoonbills']
```

**Side Note:** Recall the functionality of .sort() and .argsort()

In [7]:
import numpy as np

def sort_birds(birds, age):
    '''
    INPUT: birds, age -> 1D numpy array

    OUTPUT: result -> sorted bird 1D array
    '''

    ## STEP 1 : Get the sorted index of age.

    sorted_age_index = np.argsort(age)

    ## STEP 2: Use the index from previous step to get sorted birds

    result = birds[sorted_age_index]

    return result

birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
print(f"""
birds:
{birds}

age:
{age}

sort_birds(birds, age):
{sort_birds(birds, age)}
""")


birds:
['spoonbills' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'plovers'
 'plovers' 'Cranes' 'spoonbills']

age:
[5.5 6.  3.5 1.5 3.  4.  3.5 2.  5.5 6. ]

sort_birds(birds, age):
['plovers' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'spoonbills'
 'Cranes' 'plovers' 'spoonbills']



# **Q5. Comparing in numpy**

a. What is the last element of the output?

```python
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))
```

b. What is the output of the code snippet given below?

```python
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2
```

####**Ans:**

```
a. Ram
b. [False, False, False]
```

In [8]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

['Astha' 'Raghavendra' 'Ram']


array([False, False, False])

# **AQ1. Reshape me**

What is the below code printing?

```python
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)
```

In [9]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# **AQ2. Vectorized code**

Given 3 arrays,

```python
arr1 = np.array([1,2,3,6,3,2])
arr2 = np.array([4,2,1,3,3,2])
arr3 = np.zeros(len(arr1))
```

Which of the following are vectorized code(s) for array operations?

A.

```python
for i in range(len(arr1)):
    arr3[i] = arr1[i] * arr2[i]
```

B.

```python
arr3 = arr1*arr2
```

C.

```python
for i in range(len(arr1)):
    if(arr1[i] < 0 ):
        arr1[i] = -1
    else:
        arr1[i] = 1
```
D.

```python
np.where(arr1 > 0, 1, -1)
```

#### **Ans:**

Options B & D:
* arr3 = arr1*arr2
* np.where(arr1 > 0, 1, -1)

# **AQ3. Dot Dot Dash**

Which of the following code will NOT throw an error?

A.

```python
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)
```

B.
```python
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)
```

C.

```python
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)
```

D.

```python
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)
```

#### **Ans:**

All options work!

In [13]:
import numpy as np

# Option 1:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

# Option 2:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

# Option 3:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

# Option 4:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

# **AQ4. Swappers**

What would the following code do?

```python
import numpy as np
A = np.arange(9).reshape(3,3)
print(A[:, ::-1])
```

In [14]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


# **AQ5. Calculate Age**

**Problem Description:**

Given a list of birds and their corresponding age, calculate the mean age of the Crane bird (rounded off to 2 decimal points)

**Input Format:**

Two 1D array list i.e. bird array and age array

**Output Format:**

Float value representing mean age of crane birds

**Sample Input:**

```python
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
```

**Sample Output:**

4.75

**Note:** To round off the result, use np.round()

In [21]:
import numpy as np

def calculate_mean_age(birds, age):
    '''
    INPUT: birds, age -> 1D array

    OUPUT: mean_age -> float variable
    '''

    mean_age = None

    ## STEP1. Create mask to get Crane birds from birds array
    mask = birds == 'Cranes'

    ## STEP2. Get the age of crane birds

    crane_ages = age[mask]

    ## STEP 3. Calculate mean age of crane birds

    mean_age = np.mean(crane_ages)

    ## STEP 4. Round off the mean age to 2 decimal points

    mean_age = np.round(mean_age, 2)

    return mean_age

birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

print(f"""
birds:
{birds}

age:
{age}

calculate_mean_age(birds, age):
{calculate_mean_age(birds, age)}
""")


birds:
['spoonbills' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'plovers'
 'plovers' 'Cranes' 'spoonbills']

age:
[5.5 6.  3.5 1.5 3.  4.  3.5 2.  5.5 6. ]

calculate_mean_age(birds, age):
4.75



# **AQ6. Oldest bird**

Given a array of bird names and another array with corresponding ages of the birds, find the name of the oldest bird in the list.

**Input Format:**

Input has two lines.

* First line is the array of bird names (String).
* Second line is the array of ages of the birds (Int).

**Output Format:**

string

**Sample Input:**

```python
['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']  
[6, 1, 6, 5, 7, 6, 0, 9, 0, 7]
```

**Sample Output:**

parrot

**Explanation:**

parrot has age 9 which is the max of all the ages in the array; therefore parrot is returned.

In [23]:
import numpy as np
def oldest_bird(birds, age):
    ''' birds[i] consist of the names of the type of ith bird
        age[i] consist of the age of ith bird'''

    ## STEP 1: Get the index of maximum age element

    max_age_index = np.argmax(age)


    ## STEP 2: Get the bird with maxium age using the above index

    old_bird = birds[max_age_index]

    return old_bird

birds = np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock'])
age = np.array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])

print(f"""
birds:
{birds}

age:
{age}

oldest_bird(birds, age):
{oldest_bird(birds, age)}
""")



birds:
['sparrow' 'peacock' 'parrot' 'owl' 'peacock' 'macaw' 'macaw' 'parrot'
 'macaw' 'peacock']

age:
[6 1 6 5 7 6 0 9 0 7]

oldest_bird(birds, age):
parrot

