In [ ]:
Question 1: What will be the output of the following NumPy code?


import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[1:, 1:])

In [ ]:
A) [[50, 60], [80, 90]]
B) [[40, 50], [70, 80]]
C) [[50, 60]]
D) [[20, 30], [50, 60], [80, 90]]

In [ ]:
Question 2: You are given a sales dataset (3x3 matrix). Perform the following operations:

Find if any region had sales below 50 (np.any()).
Check if all regions had sales above 20 (np.all()).
Mark sales greater than 100 as "High", otherwise "Low" (np.where()).

In [ ]:
sales = np.array([[120, 80, 30],
              [45, 60, 150],
              [10, 110, 90]])

In [ ]:
import numpy as np

A = np.array([1, 2, 3, 4])
B = A.view()
print(A)
print(B)
B[1] = 99

# print(A)
print(B)
print(A)

[1 2 3 4]
[1 2 3 4]
[ 1 99  3  4]
[ 1 99  3  4]


In [ ]:
What will be the output?
A)
[1 2 3 4]
[1 99 3 4]

B)
[1 99 3 4]
[1 99 3 4]

C)
[1 2 3 4]
[1 2 3 4]

D) Error

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.hstack((A, B))
D = np.vstack((A, B))

print(C.shape, D.shape)

In [ ]:

A) (2, 4), (4, 2)
B) (4, 2), (2, 4)
C) (2, 2), (2, 2)
D) Error

In [ ]:
Question 8: You are given a DataFrame df containing sales data. It has duplicate
records, and you need to remove them while keeping only the first occurrence.
Then, you sort the DataFrame by the 'Revenue' column in descending order.

Which of the following Pandas operations will achieve this?



C) df.drop_duplicates(keep='first').sort_values('Revenue', ascending=True)
D) df.drop_duplicates(keep='first').sort_values('Revenue', ascending=False)

In [ ]:
You have a DataFrame containing sales transactions. You want to group by "Region"
and compute the standard deviation of sales.
However, you also need a custom transformation where each value
is scaled based on the group's max sale.

Which of the following correctly implements both?

A)df.groupby("Region")["Sales"].std().apply(lambda x: x / x.max())
B)df.groupby("Region")["Sales"].transform(lambda x: x / x.max())
C)df.groupby("Region").apply(lambda x: x["Sales"].std() / x["Sales"].max())
D)df.groupby("Region")["Sales"].agg(["std", lambda x: x / x.max()])

In [ ]:
import pandas as pd

# Sample data
data = {
    "Region": ["East", "East", "West", "West", "South", "South"],
    "Sales":  [100, 200, 150, 300, 400, 500]
}

df = pd.DataFrame(data)
df.head()

Region  Sales
0   East    100
1   East    200
2   West    150
3   West    300
4  South    400

In [ ]:
df.groupby("Region")["Sales"].std()

Region
East      70.710678
South     70.710678
West     106.066017
Name: Sales, dtype: float64

In [ ]:
df.groupby("Region")["Sales"].transform(lambda x: x / x.max())

0    0.5
1    1.0
2    0.5
3    1.0
4    0.8
5    1.0
Name: Sales, dtype: float64

In [ ]:
df.groupby("Region").apply(lambda x: x["Sales"].std() / x["Sales"].max())

<ipython-input-14-cfae56b6948d>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("Region").apply(lambda x: x["Sales"].std() / x["Sales"].max())


Region
East     0.353553
South    0.141421
West     0.353553
dtype: float64

In [ ]:
 A bank is analyzing customer loan defaults across different years and regions. You need to:

Create a pivot table showing average default rate per region & year.
Melt the pivot table to long format.
Bin default rates into categories:
Low (< 5%)
Medium (5% - 10%)
High (> 10%)

In [ ]:
df = pd.DataFrame({
"Year": [2021, 2021, 2022, 2022, 2023, 2023],
"Region": ["East", "West", "East", "West", "East", "West"],
"Default_Rate": [4.5, 8.0, 12.5, 6.0, 3.0, 15.0]
})

In [ ]:
You have a DataFrame with missing values:


df = pd.DataFrame({
"Product": ["Laptop", "Tablet", "Phone", None],
"Price": [1000, np.nan, 500, 800]})

In [ ]:
Which of the following correctly fills missing product names with "Unknown"
and fills missing prices with the column's median?

A)df = df.fillna({"Product": "Unknown", "Price": df["Price"].mean()})

B)df = df.fillna({"Product": "Unknown", "Price": df["Price"].median()})

C)df = df["Product"].fillna("Unknown", inplace=True)
df["Price"].fillna(df["Price"].median(), inplace=True)

D)df = df.replace(np.nan, {"Product": "Unknown", "Price": df["Price"].median()})

In [ ]:
Assuming all outcomes are equally likely, what is the probability of A ∪ B?

In a probability experiment, let

Event A = {1, 2, 3},
Event B = {3, 4, 5},
Sample space S = {1, 2, 3, 4, 5, 6}.
Options:
a) 3/6
b) 4/6
c) 5/6
d 6/6


In [ ]:
In a retail business, 70% of customers purchased
product A, 60% purchased product B, and 40% purchased both.
 What percentage of customers purchased either product A or B (or both)?

Options:
a) 90%
b) 100%
c) 70%
d) 60%

In [ ]:
 In a survey, 80% of users saw Ad A, and 50% saw both Ad A and Ad B.
 What is the probability that a randomly selected user saw Ad B or did not see Ad A?

Options:
a) 1.0
b) 0.9
c) 0.7
d) 0.8

In [ ]:
 A patient can be treated in Hospital A (60%), Hospital B (30%), or Hospital C (10%).
 The probability of recovery if treated in A is 0.9, in B is 0.7, and in C is 0.4.
What is the probability that a randomly selected patient recovers?

Options:
a) 0.81
b) 0.73
c) 0.83
d) 0.79

In [ ]:
A test detects a rare disease that affects 1 in 1000 people.
 The test is 99% accurate (True Positive) and gives 5% false positives.
If a person tests positive, what is the probability they actually have the disease?

Options:
a) 0.95
b) 0.2
c) 0.019
d) 0.5

In [ ]:
 Which of the following statements are true for the dataset:

data = [2, 2, 3, 8, 8, 10, 15]
Options:


C. Range = 13


In [ ]:
A team of 6 analysts is to be formed from a group of 4 male and 5 female candidates.
If the team must contain at least 2 females, how many different teams can be formed?


In [ ]:
In an email server monitoring system, the time between
two email arrivals follows an Exponential Distribution with rate λ = 2 (emails/min).

Which of the following is/are true?

A. The expected waiting time is 0.5 minutes
B. The exponential distribution is memoryless
C. The probability of receiving no email in a minute is ~13.5%
D. Exponential is symmetric and bell-shaped
E. Variance = 1/λ

In [ ]:
A tech support center receives support tickets at random times,
 and it is known that the probability of resolving a ticket in a single attempt is 0.2.
  Let X be the number of attempts until the first successful resolution (including the successful one).

Which of the following statements about this geometric distribution are correct?

Options:
A. The probability that the first successful resolution occurs on the 4th attempt is 0.1024
B. The expected number of attempts until the first success is 5
C. The probability that it takes at most 3 attempts to resolve the issue is approximately 0.488
D. The cumulative distribution function (CDF) at x = 4 is equal to P(X ≤ 4) = 0.509
E. The variance of X is 16